version: "3.9"
services:
  api:
    container_name: neurai_api
    build:
      context: .
      dockerfile: config/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - "config/api.env"
    volumes:
      - .:/neurai-api
    depends_on:
      - "db"
    networks:
      - be
      - db
    restart: always
  db:
    container_name: neurai_db
    image: postgres:latest
    env_file:
      - "config/db.env"
    restart: always
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"     # !Use only for debug conn

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/postgres'

networks:
  be:
    name: neurai-be-network
  db: