version: "3.9"
services:
  api:
    container_name: neurai_api
    build:
      context: .
      dockerfile: api/config/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - "api/config/api.env"
    volumes:
      - /var/log/neurai:/var/log/neurai
    depends_on:
      - "db"
    networks:
      - be
      - db
    restart: always

  db:
    container_name: neurai_db
    image: postgres:15
    env_file:
      - "api/config/db.env"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/postgres'

networks:
  be:
    name: neurai-be-network
  db:
