# https://book.orthanc-server.com/users/docker-osimis.html
version: "3"
services:
  pacs:
    image: osimis/orthanc
    restart: unless-stopped
    ports:
      - "11112:11112"
      - "8010:8010"
    volumes:
      - "orthanc-storage:/var/lib/orthanc/db:Z"
    networks:
      - be
    environment:
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
    secrets:
        - "orthanc.json"

secrets:
  orthanc.json:
    file: site_api/config/orthanc.json

volumes:
  orthanc-storage:


networks:
  be:
    external:
      name: neurai-be-network
