name: NeurAI-API Pull Request Pipeline

on:
  pull_request:
    branches: [master]

jobs:
  test-pr-be:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Check branch name
        uses: ./.github/actions/check-branch-name
        id: branch-name-check
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          regex: '^NAI-(\d+)\/(feat|fix|enhc)\d*$'

      - name: Install Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'config/requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r config/requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Calculate version tag
        if: ${{ steps.branch-name-check.outputs.semantic-type != '' }}
        id: version-tag
        uses: craig-day/compute-tag@v14
        with:
          github_token: ${{ github.token }}
          version_type: ${{ steps.branch-name-check.outputs.semantic-type }}

      - name: Add label of semantic type to PR
        if: ${{ steps.branch-name-check.outputs.semantic-type != '' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.branch-name-check.outputs.semantic-type }}

      - name: Add version to PR comment
        if: ${{ steps.branch-name-check.outputs.semantic-type != '' }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Branch type: ${{ steps.branch-name-check.outputs.type }} (${{ steps.branch-name-check.outputs.semantic-type }})
            Previous tag: ${{ steps.version-tag.outputs.previous_tag }}
            Next tag: ${{ steps.version-tag.outputs.next_tag }}
